# GitHub Sponsors & Funding for MemGuard
# World's first ML-powered AutoFix for memory leaks

# PayPal donation link for MemGuard project support
custom: ["https://www.paypal.com/donate/?business=Y9ULBRWNG9EVL&no_recurring=0&item_name=World%27s+first+ML-powered+AutoFix+and+Detect+for+memory+leaks+in+runtime+Python+apps.+Support+revolutionary+open+source+AI+tech%21&currency_code=CAD"]